<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Join_our_team</name>
   <tag></tag>
   <elementGuidId>811828af-f1e0-4d63-a61b-367d5e4c1c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='cx-header']/cx-page-layout/cx-page-slot[3]/app-dynamic-cms-component-wrapper/app-navigation-bar/div[2]/ul/li[7]/ul/li[3]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
