<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StickyBanner</name>
   <tag></tag>
   <elementGuidId>3d07133c-cb34-4fdd-ad64-a9efbf9f0569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-layout[@section=&quot;header&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
