<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Availability dropdown</name>
   <tag></tag>
   <elementGuidId>0b314408-47bb-43f6-b602-e054493c9be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jot-avail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jot-avail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Availability*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8796e889-d0c1-44b4-aff5-e12ef77a3949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jot-avail</value>
      <webElementGuid>681395fb-aea8-4486-aa3d-ff048190664b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>availability.code</value>
      <webElementGuid>4b625602-3928-48b5-b1db-cfea9241d1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tell us your availability...Immediate1-2 MonthsAfter 2 Months</value>
      <webElementGuid>74596e5c-a8f3-4316-a652-ff7010366d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jot-avail&quot;)</value>
      <webElementGuid>1eadf725-57bd-4c2e-bef6-3252495b5527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jot-avail']</value>
      <webElementGuid>c849535f-f1cf-46ce-a9ec-0690b40e18c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinOurTeamForm']/div/div[4]/div[2]/select</value>
      <webElementGuid>8cd75d10-4f95-43eb-a72b-5c5f45f652e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Availability*'])[1]/following::select[1]</value>
      <webElementGuid>a6b07b4f-f576-46c1-abca-38557372872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current or Previous Job Title*'])[1]/following::select[1]</value>
      <webElementGuid>59d3156a-3e10-41c6-b2dc-f2edc8ea0f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resume (PDF or Word Document)*'])[1]/preceding::select[1]</value>
      <webElementGuid>e42a7e36-d059-4be6-a9e4-a627dd3f4827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::select[1]</value>
      <webElementGuid>ac7aba2f-959c-4feb-b015-4752c63da9c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>5cd5908f-51ed-4bc2-aed1-a1bc706e8672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jot-avail' and @name = 'availability.code' and (text() = 'Tell us your availability...Immediate1-2 MonthsAfter 2 Months' or . = 'Tell us your availability...Immediate1-2 MonthsAfter 2 Months')]</value>
      <webElementGuid>2884da74-81ac-4601-a73e-7af051d39c57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
