<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country text</name>
   <tag></tag>
   <elementGuidId>42b58783-652d-4fbb-b7f9-2db66437ce4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='joinOurTeamForm']/div/div[3]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-row > div.form-input > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Country*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>105a201b-95b0-41ca-86af-3ce78ec98b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>jot-country</value>
      <webElementGuid>6144e422-03e4-410d-9630-05cebd9f1ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Country*</value>
      <webElementGuid>10e2775e-1e36-46ed-a31e-e80d7c9d65e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joinOurTeamForm&quot;)/div[@class=&quot;form-fields&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-input&quot;]/label[1]</value>
      <webElementGuid>5a7732e6-69ea-42f1-bb2a-312e6a9e307b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinOurTeamForm']/div/div[3]/div/label</value>
      <webElementGuid>aaad6b03-147d-4cb7-baed-3dfcaf26eefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone*'])[1]/following::label[1]</value>
      <webElementGuid>5bfbcaeb-5435-4ae7-84eb-4c04ce74c6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email*'])[1]/following::label[2]</value>
      <webElementGuid>96af14be-181f-4710-a157-869f5788e6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State*'])[1]/preceding::label[1]</value>
      <webElementGuid>59dfd4b2-6c32-4054-ae1e-17d53bd8cf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current or Previous Job Title*'])[1]/preceding::label[2]</value>
      <webElementGuid>baa539aa-7de8-441a-a9a6-138c1622a945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Country*']/parent::*</value>
      <webElementGuid>3ed20c9d-0bce-40f8-a0bc-c025495a13b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/label</value>
      <webElementGuid>185d1ec3-a514-4858-843f-3ff50b98e6b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Country*' or . = 'Country*')]</value>
      <webElementGuid>e7baa9ed-2afb-4729-a507-4a4c8bd8493f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
