<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchLens</name>
   <tag></tag>
   <elementGuidId>c9660960-b193-4ed7-b44f-ad3ff919ccda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//cx-page-slot[@position='SearchBox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
