<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Resume (PDF or Word Document)_resume</name>
   <tag></tag>
   <elementGuidId>e03d1fc2-6100-4717-81f0-89c760dbe19c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resume']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resume</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Resume (PDF or Word Document)*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3166a18-f20e-4e27-854f-3cb13f772c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>fe26aafb-7654-4732-a592-7cd26362ae9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>0a60a249-9790-49ef-9675-e4fb448b9826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>75abc543-12c4-465e-99d7-f99f450634d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Attach your resume...</value>
      <webElementGuid>b7437544-92e3-49ea-a482-bef3d1de5b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resume&quot;)</value>
      <webElementGuid>22947558-28ca-4c81-b20a-03ed3e6ffb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resume']</value>
      <webElementGuid>4c8c01b7-167c-4e8c-b650-d561aadab756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='joinOurTeamForm']/div/div[5]/div/div/input</value>
      <webElementGuid>5bf90e0e-9609-4f58-9f8d-31d09b668534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>d8777de3-698a-4e28-98e7-b0f7fbc16a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'resume' and @name = 'resume' and @placeholder = 'Attach your resume...']</value>
      <webElementGuid>f523da51-a591-4147-bef3-6e9756ccf299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
